name: checksum

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
            method: md5
            patterns: |
                *.zip
                *.tar.gz
      - name: Upload checksum
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: checksum.txt
          asset_name: md5.txt
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
